const ORDER_STATUS = {
  AWAITING_PAYMENT: 'AGUARDANDO_PAGAMENTO',
  PAID: 'PAGO',
  PREPARING: 'PREPARING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

const INITIAL_ORDER_STATUS = ORDER_STATUS.AWAITING_PAYMENT;

module.exports = {
  ORDER_STATUS,
  INITIAL_ORDER_STATUS,
};
